<?php defined('SYSPATH') or die('No direct script access.'); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb" lang="en-gb" dir="ltr" >
<head>
	<title><?php echo isset($head) ? $head->title() : '';?></title>
	<base href="<?php echo URL::site()?>" />
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="copyright" content="Nguyễn Văn Nguyên" />
	<meta name="author" content="Nguyễn Văn Nguyên" />

	<?php 
		echo HTML::script('min/js/admin');
		echo $head->script_files();
		echo $head->script_vars();
		echo $head->scripts();
	?>

	<script type="text/javascript">
	/*<![CDATA[*/
		jQuery(function(){
			jQuery('#loading').ajaxComplete(function(){
				jQuery('#loading').hide();
			});
			jQuery('#loading').ajaxStart(function(){
				jQuery('#loading').show();
			});

			jQuery("#toggle_all").click(function(){
				var elements = jQuery("form#adminForm :checkbox[name*=chk_id]");
				document.adminForm.box_checked.value = 0;
				if (this.checked) {
					document.adminForm.box_checked.value = elements.length;
					elements.each(function (element) {
						this.checked = true;
					});
				} else {
					elements.each(function (element) {
						this.checked = false;
					});
				}
			});
		});

		function enable_async() {
			jQuery.ajaxSetup({
				async: true
			});
		}

		function disable_async() {
			jQuery.ajaxSetup({
				async: false
			});
		}

		function id_checked(checked){
			var the_form = document.adminForm;
			if (checked) {
				the_form.box_checked.value++;
			} else {
				the_form.box_checked.value--;
			}
			if (the_form.box_checked.value == 0) {
				the_form.toggle_all.checked = false;
			}
			if (the_form.box_checked.value == jQuery("form#adminForm :checkbox[name*=chk_id]").length) {
				the_form.toggle_all.checked = true;
			}
		}
	/*]]>*/
	</script>

	<?php 
		echo HTML::style('min/css/admin');
	?>
	<!--[if IE 7]>
	<?php echo HTML::style('contents/admin/css/ie7.css');?>
	<![endif]-->
	<!--[if lte IE 6]>
	<?php echo HTML::style('contents/admin/css/ie6.css');?>
	<![endif]-->
	<?php
		echo $head->style_files();
		echo $head->styles();
	?>

	<style type="text/css">
		.bold{
			font-style: bold;
			font-weight: bold;
			color: #000;
		}
		form#adminForm label.error{
			color: red;
			font-style: italic;
			font-size: 1.0em;
			font-weight: normal;
		}
		form#adminForm label.error { display: none;}
	</style>

</head>
<body id="minwidth-body" >
<div id="border-top" class="green"><div><div>
	<span class="version"></span>
	<span class="title">Quản trị hệ thống</span>
</div></div></div>
<div id="header-box">
	<div id="module-status">
		<span class="loggedin-users">
			<?php echo Auth::instance()->get_user()->full_name;?>
		</span>
		<span class="loggedin-users"><?php echo HTML::anchor('admin/user/change_password', 'Đổi mật khẩu');?></span>
		<span class="logout"><?php echo HTML::anchor('admin/login/logout', 'Đăng xuất');?></span>
	</div>
	<div id="module-menu">
		<?php echo Request::factory('admin/menu')->execute()->send_headers()->body();?>
	</div>
	<div class="clr"></div>
</div>
<?php echo isset($content) ? $content : ''; ?>
<div id="border-bottom"><div><div></div></div></div>
<div id="footer">
	<p class="copyright"><?php echo __('Loaded in {execution_time} seconds, using {memory_usage} of memory. Generated by Kohana v{kohana_version}'); ?></p>
</div>
<div id="dialog_confirm" title="" style="display:none;text-align:center;font-size:14px;font-weight: bold;"></div>
<div id="loading" style="display:none;text-align:center;position:fixed;left:50%;top:120px;overflow:auto;z-index:1000">
<?php
	echo HTML::image('contents/admin/images/ajax_loading.gif', array(
				'border' => '0',
				'alt' => 'Đang tải...',
			));
?>
</div>
</body>
</html>