<?php defined('SYSPATH') or die('No direct script access.'); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb" lang="en-gb" dir="ltr" >
<head>
	<title>Đăng nhập hệ thống</title>
	<!--base href="<?php echo URL::site()?>" /-->
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="copyright" content="Bản quyền Nguyễn Văn Nguyên" />
	<meta name="author" content="Nguyễn Văn Nguyên" />

	<?php
		echo HTML::script('min/js/login');
		echo HTML::style('min/css/login');
	?>

	<!--[if IE 7]>
	<?php echo HTML::style('contents/admin/css/ie7.css');?>
	<![endif]-->
	<!--[if lte IE 6]>
	<?php echo HTML::style('contents/admin/css/ie6.css');?>
	<![endif]-->

<style type="text/css">
form#form-login label.error, label.error {
	color: red;
	font-style: italic;
	font-size: 1.0em;
	font-weight: normal;
	text-align: left;
}
</style>
<script language="javascript" type="text/javascript">
/*<![CDATA[*/
	function setFocus(){
		jQuery('#username').select();
		jQuery('#username').focus();
	}
	jQuery(function() {
		setFocus();
		jQuery('#form-login').submit(function(){
			jQuery('#md5_password').val(hex_md5(jQuery('#password').val()));
			jQuery('#password').val('');
		});

		jQuery('#lnk_login').click(function(){
			jQuery('#form-login').submit();
		});

		jQuery("#form-login").validate({
			rules: {
				user_name: "required"
			},
			messages: {
				user_name: 'Hãy nhập tên truy cập'
			}
		});
	});
/*]]>*/
</script>
</head>
<body>
<div id="border-top" class="green"><div><div>
	<span class="title">Đăng nhập hệ thống</span>
</div></div></div>

<div id="content-box"><div class="padding">
	<div id="element-box" class="login"><div class="t"><div class="t"><div class="t"></div></div></div><div class="m">
		<h1>Đăng nhập hệ thống</h1>
		<div id="section-box"><div class="t"><div class="t"><div class="t"></div></div></div><div class="m">
			<?php echo Form::open('admin/login/redirect', array('id' => 'form-login', 'name' => 'login', 'style' => 'clear: both;', ))?>
			<p id="form-login-username">
			<?php
				echo Form::label('user_name', 'Tên truy cập');
				echo Form::input('user_name', '', array(
							'id' => 'user_name',
							'class' => 'inputbox',
							'size' => '15',
						));
			?>
			</p>
			<p id="form-login-password">
			<?php
				echo Form::label('password', 'Mật khẩu');
				echo Form::password('password', '', array(
							'id' => 'password',
							'class' => 'inputbox',
							'size' => '15',
						));
			?>
			</p>
			<p id="form-login-remember">
			<?php
				echo Form::label('remember', 'Ghi nhớ đăng nhập');
				echo Form::checkbox('remember', '', FALSE, array(
							'id' => 'remember',
							'class' => 'inputbox',
							'style' => 'width:10px;',
						));
			?>
			</p>
			<div class="button_holder"><div class="button1"><div class="next">
				<a id="lnk_login">Đăng nhập</a>
			</div></div></div>
			<div class="clr"></div>
			<input type="submit" style="border: 0; padding: 0; margin: 0; width: 0px; height: 0px;" value="Đăng nhập" />
			<?php 
				echo Form::hidden('md5_password', '', array('id'=>'md5_password',));
				echo Form::hidden('return_url', empty($return_url) ? '' : $return_url, array('id'=>'return_url',));
			?>
			<?php echo Form::close(); ?>
			<div class="clr"></div>
		</div><div class="b"><div class="b"><div class="b"></div></div></div></div>
		<p>Sử dụng tên truy cập và mật khẩu hợp lệ để truy cập vào Quản trị</p>
		<p><a href="<?php echo URL::base()?>">Trở về trang chủ</a></p>
		<div id="lock"></div>
		<div class="clr"></div>
	</div><div class="b"><div class="b"><div class="b"></div></div></div></div>
	<noscript>Warning! JavaScript must be enabled for proper operation of the Administrator back-end.</noscript>
	<div class="clr"></div>
</div></div>
<div id="border-bottom"><div><div></div></div></div>
<div id="footer">
	<p class="copyright"><?php echo __('Loaded in {execution_time} seconds, using {memory_usage} of memory. Generated by Kohana v{kohana_version}.'); ?></p>
</div>
</body>
</html>
